name: YouTube Trending Daily ETL

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 2:30 AM UTC
  workflow_dispatch:      # Enables manual trigger from GitHub UI

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas pyodbc python-dotenv

      - name: Install ODBC Driver 17 (SQL Server driver)
        run: |
          sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

      - name: Scrape YouTube Trending Data
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python scraper.py

      - name: Insert Data into Azure SQL
        env:
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
        run: python data_insert.py
